public class Connor {
    private int age;
    private String nickname;
    private int grade;
    private int weight;
    private double height;

    public Connor(int age, String nickname, int grade, int weight, double height) {
        this.age = age;
        this.nickname = nickname;
        this.grade = grade;
        this.weight = weight;
        this.height = height;
    }

    public void setNickname(int nickname) {
        this.nickname = nickname;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setGrade(int Grade) {
        this.grade = grade;
    }

    public void setAge(int height) {
        this.height = height;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }



}